global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api_gateway:8000']

  - job_name: 'stt_worker_base'
    static_configs:
      - targets: ['stt_worker_base:8001']

  - job_name: 'stt_worker_fast'
    static_configs:
      - targets: ['stt_worker_fast:8003']

  - job_name: 'stt_worker_large'
    static_configs:
      - targets: ['stt_worker_large:8004']

  - job_name: 'stt_worker_whisperx'
    static_configs:
      - targets: ['stt_worker_whisperx:8005']